language: python
python:
- '3.8.2'
cache: pip
addons:
  postgresql: '10'
before_install:
- openssl aes-256-cbc -K $encrypted_b2bef351ff2e_key -iv $encrypted_b2bef351ff2e_iv -in openstax/settings/local.py.enc -out openstax/settings/local.py -d
- pip install coverage
- pip install codecov
install:
- pip install -r requirements/dev.txt
before_script:
- createdb -U postgres openstax
script:
- coverage run manage.py test --verbosity=2 --settings=openstax.settings.test
after_success:
- codecov
notifications:
  email: false
sudo: false
